### ISSUE TITLE
About the new post import script

### ISSUE THREAD

**Issue by mrjshzk** [stechyo/godot-steam-audio#52] opened 2024-04-27 20:07 UTC
**Are you using the provided fork of Godot?**
Yes

**Godot-steam-audio version**
Latest

**Steam-Audio version**
Latest

**Operating System**
Windows 11

The current post import script it not working for me, maybe I'm mis-using it?

![image](https://github.com/stechyo/godot-steam-audio/assets/115943663/625514a5-f8b4-4433-9efb-6344e849a48b)
![image](https://github.com/stechyo/godot-steam-audio/assets/115943663/445d684e-9c6f-409d-b3b9-f53d18cdd5ca)
![image](https://github.com/stechyo/godot-steam-audio/assets/115943663/a8d3cd3f-640c-421d-8ed4-d2a8a01906f7)

**Comment by stechyo** [comment] 2024-04-27 20:17
Is “map” a gltf scene? You have to set the post import script in the import window in Godot.

**Comment by mrjshzk** [comment] 2024-04-27 20:20
Oh.. I didn't know you had to manually set the script. It worked now, thanks! Another question - how should a name for an object be to add colliders and steam audio geometry?

**Comment by mrjshzk** [comment] 2024-04-28 00:09
Ok there's a somewhat of a bug currently. If you try to name something like "my_object-col-sasg" it will create a SteamAudioGeometry but not the corresponding collision. If you write it like this "my_object-sasg-col" it will work as intented. As I understand this means "-sasg" should be the first import hint. This is probably not up to you though but with Godot itself and how it handles these things

**Comment by stechyo** [comment] 2024-04-28 09:19
Hi, I only got the time now to actually update the wiki with a [guide](https://github.com/stechyo/godot-steam-audio/wiki/Importing-meshes) for this import hint. As you noticed, a specific order is required for combining built-in hints with extension hints.  
This is because Godot will only pick up the built-in hints and effectively remove the suffix if the built-in suffix really is the last part of the name, and only then will the extension's script do its thing.  
This is not a bug but simply something I can't work around, now that there is proper documentation for this feature I'm closing this (any suggestions for documentation are appreciated ofc)

**Closed as completed by stechyo** 2024-04-28 09:19 UTC
